application:
  actions: actions
  runtimeManifest:
    packages:
      weather:
        license: Apache-2.0
        actions:
          get-weather:
            function: actions/get-weather/index.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
              CITY: $CITY
            annotations:
              require-adobe-auth: false
              final: true
